name: Standalone-Dispatch-By_User

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch/ref for integration tests'
        required: true
        default: 'develop'
      oraccrsctag:
        description: 'Tag for the crosscompiler resources'
        required: true
        default: 'tag # from ora-cc-rsc repo'

jobs:
  docker:
    if: ${{ github.repository == 'OpenRoberta/openroberta-lab' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up QEMU for multi architecture build
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get tag name
        id: getTagName
        # Parse version number without ORA prefix
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/ORA-}
      - name: Build docker image for standalone
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Docker/openroberta/conf/y-standalone-lab/Dockerfile
          platforms: linux/arm/v7, linux/amd64
          push: true
          tags: openroberta/standalone:latest, openroberta/standalone:${{ steps.getTagName.outputs.tag }}
#      - name: Build docker image for the lab server
#        if: ${{ false }}  # disable for now
#        uses: docker/build-push-action@v3
#        with:
#          builder: ${{ steps.buildx.outputs.name }}
#          context: .
#          file: ./Docker/openroberta/conf/y-docker-for-lab-ci/Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: openroberta/server:${{ steps.getTagName.outputs.tag }}
