name: IntegrationTest-Scheduled

# the ora-cc-rsc tag number (currently 32) is used twice in this workflow

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  integration-test:
    if: ${{ github.repository == 'OpenRoberta/openroberta-lab' }}
    runs-on: ubuntu-latest
    container: openroberta/base-x64:32 # ora-cc-rsc tag number
    steps:
      - name: branch ${{ github.ref }}, repo ${{ github.repository }}, ora-cc-rsc-tag 32 # ora-cc-rsc tag number
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run integration tests
        run: mvn --batch-mode clean install -PrunIT
